# Generated by Django 5.2.6 on 2025-10-09 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_branch_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='description',
            field=models.CharField(max_length=100),
        ),
    ]
