# Generated by Django 5.2.6 on 2025-10-02 17:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='likes',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='likes',
            field=models.ManyToManyField(related_name='likes_db', to=settings.AUTH_USER_MODEL),
        ),
    ]
